version: '3.8'

services:
  mongo:
    container_name: mongo
    image: bitnami/mongodb:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    networks:
      - platform

  redis:
    container_name: redis
    image: bitnami/redis:7.0
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - platform

networks:
  platform:
    driver: bridge
